/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddResourceRequest,
  CreateSpecRequest,
  LastEditedLocationResponse,
  ProblemDetail,
  ResourceResponse,
  SpecDetailResponse,
  SpecListResponse,
  SpecSummaryResponse,
  Uuid
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listSpecsResponse200 = {
  data: SpecListResponse
  status: 200
}

export type listSpecsResponse401 = {
  data: void
  status: 401
}

export type listSpecsResponse403 = {
  data: void
  status: 403
}

export type listSpecsResponseSuccess = (listSpecsResponse200) & {
  headers: Headers;
};
export type listSpecsResponseError = (listSpecsResponse401 | listSpecsResponse403) & {
  headers: Headers;
};

export type listSpecsResponse = (listSpecsResponseSuccess | listSpecsResponseError)

export const getListSpecsUrl = () => {




  return `/api/v1/specs`
}

/**
 * @summary List all APIs as summary projections (ADR-0008)
 */
export const listSpecs = async ( options?: RequestInit): Promise<listSpecsResponse> => {

  return customFetch<listSpecsResponse>(getListSpecsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSpecsQueryKey = () => {
    return [
    `/api/v1/specs`
    ] as const;
    }


export const getListSpecsQueryOptions = <TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSpecsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSpecs>>> = ({ signal }) => listSpecs({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSpecsQueryResult = NonNullable<Awaited<ReturnType<typeof listSpecs>>>
export type ListSpecsQueryError = void


export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSpecs>>,
          TError,
          Awaited<ReturnType<typeof listSpecs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSpecs>>,
          TError,
          Awaited<ReturnType<typeof listSpecs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all APIs as summary projections (ADR-0008)
 */

export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSpecsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createSpecResponse201 = {
  data: SpecSummaryResponse
  status: 201
}

export type createSpecResponse400 = {
  data: ProblemDetail
  status: 400
}

export type createSpecResponse401 = {
  data: void
  status: 401
}

export type createSpecResponse403 = {
  data: void
  status: 403
}

export type createSpecResponseSuccess = (createSpecResponse201) & {
  headers: Headers;
};
export type createSpecResponseError = (createSpecResponse400 | createSpecResponse401 | createSpecResponse403) & {
  headers: Headers;
};

export type createSpecResponse = (createSpecResponseSuccess | createSpecResponseError)

export const getCreateSpecUrl = () => {




  return `/api/v1/specs`
}

/**
 * @summary Create a new, empty API (FEAT-003)
 */
export const createSpec = async (createSpecRequest: CreateSpecRequest, options?: RequestInit): Promise<createSpecResponse> => {

  return customFetch<createSpecResponse>(getCreateSpecUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSpecRequest)
  }
);}





export const getCreateSpecMutationOptions = <TError = ProblemDetail | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSpec>>, TError,{data: CreateSpecRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createSpec>>, TError,{data: CreateSpecRequest}, TContext> => {

const mutationKey = ['createSpec'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSpec>>, {data: CreateSpecRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSpec(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSpecMutationResult = NonNullable<Awaited<ReturnType<typeof createSpec>>>
    export type CreateSpecMutationBody = CreateSpecRequest
    export type CreateSpecMutationError = ProblemDetail | void

    /**
 * @summary Create a new, empty API (FEAT-003)
 */
export const useCreateSpec = <TError = ProblemDetail | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSpec>>, TError,{data: CreateSpecRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSpec>>,
        TError,
        {data: CreateSpecRequest},
        TContext
      > => {
      return useMutation(getCreateSpecMutationOptions(options), queryClient);
    }
    export type getLastEditedLocationResponse200 = {
  data: LastEditedLocationResponse
  status: 200
}

export type getLastEditedLocationResponse204 = {
  data: void
  status: 204
}

export type getLastEditedLocationResponse401 = {
  data: void
  status: 401
}

export type getLastEditedLocationResponse403 = {
  data: void
  status: 403
}

export type getLastEditedLocationResponseSuccess = (getLastEditedLocationResponse200 | getLastEditedLocationResponse204) & {
  headers: Headers;
};
export type getLastEditedLocationResponseError = (getLastEditedLocationResponse401 | getLastEditedLocationResponse403) & {
  headers: Headers;
};

export type getLastEditedLocationResponse = (getLastEditedLocationResponseSuccess | getLastEditedLocationResponseError)

export const getGetLastEditedLocationUrl = () => {




  return `/api/v1/specs/last-edited`
}

/**
 * @summary The current user's last-edited location, powering jump-back-in
 */
export const getLastEditedLocation = async ( options?: RequestInit): Promise<getLastEditedLocationResponse> => {

  return customFetch<getLastEditedLocationResponse>(getGetLastEditedLocationUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLastEditedLocationQueryKey = () => {
    return [
    `/api/v1/specs/last-edited`
    ] as const;
    }


export const getGetLastEditedLocationQueryOptions = <TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLastEditedLocationQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLastEditedLocation>>> = ({ signal }) => getLastEditedLocation({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLastEditedLocationQueryResult = NonNullable<Awaited<ReturnType<typeof getLastEditedLocation>>>
export type GetLastEditedLocationQueryError = void


export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLastEditedLocation>>,
          TError,
          Awaited<ReturnType<typeof getLastEditedLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLastEditedLocation>>,
          TError,
          Awaited<ReturnType<typeof getLastEditedLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The current user's last-edited location, powering jump-back-in
 */

export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLastEditedLocationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getSpecResponse200 = {
  data: SpecDetailResponse
  status: 200
}

export type getSpecResponse401 = {
  data: void
  status: 401
}

export type getSpecResponse403 = {
  data: void
  status: 403
}

export type getSpecResponse404 = {
  data: ProblemDetail
  status: 404
}

export type getSpecResponseSuccess = (getSpecResponse200) & {
  headers: Headers;
};
export type getSpecResponseError = (getSpecResponse401 | getSpecResponse403 | getSpecResponse404) & {
  headers: Headers;
};

export type getSpecResponse = (getSpecResponseSuccess | getSpecResponseError)

export const getGetSpecUrl = (specId: Uuid,) => {




  return `/api/v1/specs/${specId}`
}

/**
 * @summary One API with its resources and their capabilities (FEAT-005 AC8)
 */
export const getSpec = async (specId: Uuid, options?: RequestInit): Promise<getSpecResponse> => {

  return customFetch<getSpecResponse>(getGetSpecUrl(specId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSpecQueryKey = (specId: Uuid,) => {
    return [
    `/api/v1/specs/${specId}`
    ] as const;
    }


export const getGetSpecQueryOptions = <TData = Awaited<ReturnType<typeof getSpec>>, TError = void | ProblemDetail>(specId: Uuid, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpec>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSpecQueryKey(specId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSpec>>> = ({ signal }) => getSpec(specId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: specId !== null && specId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSpec>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSpecQueryResult = NonNullable<Awaited<ReturnType<typeof getSpec>>>
export type GetSpecQueryError = void | ProblemDetail


export function useGetSpec<TData = Awaited<ReturnType<typeof getSpec>>, TError = void | ProblemDetail>(
 specId: Uuid, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpec>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpec>>,
          TError,
          Awaited<ReturnType<typeof getSpec>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpec<TData = Awaited<ReturnType<typeof getSpec>>, TError = void | ProblemDetail>(
 specId: Uuid, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpec>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpec>>,
          TError,
          Awaited<ReturnType<typeof getSpec>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpec<TData = Awaited<ReturnType<typeof getSpec>>, TError = void | ProblemDetail>(
 specId: Uuid, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpec>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary One API with its resources and their capabilities (FEAT-005 AC8)
 */

export function useGetSpec<TData = Awaited<ReturnType<typeof getSpec>>, TError = void | ProblemDetail>(
 specId: Uuid, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpec>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSpecQueryOptions(specId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type addResourceResponse201 = {
  data: ResourceResponse
  status: 201
}

export type addResourceResponse400 = {
  data: ProblemDetail
  status: 400
}

export type addResourceResponse401 = {
  data: void
  status: 401
}

export type addResourceResponse403 = {
  data: void
  status: 403
}

export type addResourceResponse404 = {
  data: ProblemDetail
  status: 404
}

export type addResourceResponse409 = {
  data: ProblemDetail
  status: 409
}

export type addResourceResponseSuccess = (addResourceResponse201) & {
  headers: Headers;
};
export type addResourceResponseError = (addResourceResponse400 | addResourceResponse401 | addResourceResponse403 | addResourceResponse404 | addResourceResponse409) & {
  headers: Headers;
};

export type addResourceResponse = (addResourceResponseSuccess | addResourceResponseError)

export const getAddResourceUrl = (specId: Uuid,) => {




  return `/api/v1/specs/${specId}/resources`
}

/**
 * @summary Add a resource; its operations derive from the chosen capabilities per ADR-0010 (FEAT-005)
 */
export const addResource = async (specId: Uuid,
    addResourceRequest: AddResourceRequest, options?: RequestInit): Promise<addResourceResponse> => {

  return customFetch<addResourceResponse>(getAddResourceUrl(specId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addResourceRequest)
  }
);}





export const getAddResourceMutationOptions = <TError = ProblemDetail | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addResource>>, TError,{specId: Uuid;data: AddResourceRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addResource>>, TError,{specId: Uuid;data: AddResourceRequest}, TContext> => {

const mutationKey = ['addResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addResource>>, {specId: Uuid;data: AddResourceRequest}> = (props) => {
          const {specId,data} = props ?? {};

          return  addResource(specId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddResourceMutationResult = NonNullable<Awaited<ReturnType<typeof addResource>>>
    export type AddResourceMutationBody = AddResourceRequest
    export type AddResourceMutationError = ProblemDetail | void

    /**
 * @summary Add a resource; its operations derive from the chosen capabilities per ADR-0010 (FEAT-005)
 */
export const useAddResource = <TError = ProblemDetail | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addResource>>, TError,{specId: Uuid;data: AddResourceRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addResource>>,
        TError,
        {specId: Uuid;data: AddResourceRequest},
        TContext
      > => {
      return useMutation(getAddResourceMutationOptions(options), queryClient);
    }
