/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  LastEditedLocationResponse,
  SpecListResponse
} from '../../model';

import { customFetch } from '../../mutator/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listSpecsResponse200 = {
  data: SpecListResponse
  status: 200
}

export type listSpecsResponse401 = {
  data: void
  status: 401
}

export type listSpecsResponse403 = {
  data: void
  status: 403
}

export type listSpecsResponseSuccess = (listSpecsResponse200) & {
  headers: Headers;
};
export type listSpecsResponseError = (listSpecsResponse401 | listSpecsResponse403) & {
  headers: Headers;
};

export type listSpecsResponse = (listSpecsResponseSuccess | listSpecsResponseError)

export const getListSpecsUrl = () => {




  return `/api/v1/specs`
}

/**
 * @summary List all APIs as summary projections (ADR-0008)
 */
export const listSpecs = async ( options?: RequestInit): Promise<listSpecsResponse> => {

  return customFetch<listSpecsResponse>(getListSpecsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSpecsQueryKey = () => {
    return [
    `/api/v1/specs`
    ] as const;
    }


export const getListSpecsQueryOptions = <TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSpecsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSpecs>>> = ({ signal }) => listSpecs({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSpecsQueryResult = NonNullable<Awaited<ReturnType<typeof listSpecs>>>
export type ListSpecsQueryError = void


export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSpecs>>,
          TError,
          Awaited<ReturnType<typeof listSpecs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSpecs>>,
          TError,
          Awaited<ReturnType<typeof listSpecs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all APIs as summary projections (ADR-0008)
 */

export function useListSpecs<TData = Awaited<ReturnType<typeof listSpecs>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSpecs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSpecsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getLastEditedLocationResponse200 = {
  data: LastEditedLocationResponse
  status: 200
}

export type getLastEditedLocationResponse204 = {
  data: void
  status: 204
}

export type getLastEditedLocationResponse401 = {
  data: void
  status: 401
}

export type getLastEditedLocationResponse403 = {
  data: void
  status: 403
}

export type getLastEditedLocationResponseSuccess = (getLastEditedLocationResponse200 | getLastEditedLocationResponse204) & {
  headers: Headers;
};
export type getLastEditedLocationResponseError = (getLastEditedLocationResponse401 | getLastEditedLocationResponse403) & {
  headers: Headers;
};

export type getLastEditedLocationResponse = (getLastEditedLocationResponseSuccess | getLastEditedLocationResponseError)

export const getGetLastEditedLocationUrl = () => {




  return `/api/v1/specs/last-edited`
}

/**
 * @summary The current user's last-edited location, powering jump-back-in
 */
export const getLastEditedLocation = async ( options?: RequestInit): Promise<getLastEditedLocationResponse> => {

  return customFetch<getLastEditedLocationResponse>(getGetLastEditedLocationUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLastEditedLocationQueryKey = () => {
    return [
    `/api/v1/specs/last-edited`
    ] as const;
    }


export const getGetLastEditedLocationQueryOptions = <TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLastEditedLocationQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLastEditedLocation>>> = ({ signal }) => getLastEditedLocation({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLastEditedLocationQueryResult = NonNullable<Awaited<ReturnType<typeof getLastEditedLocation>>>
export type GetLastEditedLocationQueryError = void


export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLastEditedLocation>>,
          TError,
          Awaited<ReturnType<typeof getLastEditedLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLastEditedLocation>>,
          TError,
          Awaited<ReturnType<typeof getLastEditedLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The current user's last-edited location, powering jump-back-in
 */

export function useGetLastEditedLocation<TData = Awaited<ReturnType<typeof getLastEditedLocation>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastEditedLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLastEditedLocationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






