/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { Capability } from './capability';

export interface AddResourceRequest {
  /**
     * The noun; becomes the schema name (PascalCase) and, pluralized, the collection path
     * @maxLength 100
     * @pattern ^[A-Za-z][A-Za-z0-9]*( [A-Za-z0-9]+)*$
     */
  name: string;
  /** Becomes the schema description; omitted from the document when blank */
  description?: string;
  /**
     * The chosen standard capabilities (ADR-0010); duplicates are ignored
     * @minItems 1
     */
  capabilities: Capability[];
}
