/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { FailureAnswerResponse } from './failureAnswerResponse';

export interface AnswersFacetResponse {
  successStatus?: string;
  successDescription?: string;
  failures?: FailureAnswerResponse[];
}
