/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { Capability } from './capability';

export interface CapabilityResponse {
  capability?: Capability;
  label?: string;
  method?: string;
  path?: string;
}
