/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { AnswersFacetResponse } from './answersFacetResponse';
import type { CapabilityResponse } from './capabilityResponse';
import type { DeclarationResponse } from './declarationResponse';
import type { HeadersFacetResponse } from './headersFacetResponse';
import type { PagingFacetResponse } from './pagingFacetResponse';
import type { RequestFacetResponse } from './requestFacetResponse';

export interface CapabilityContractResponse {
  capability?: CapabilityResponse;
  description?: string;
  singularNoun?: string;
  request?: RequestFacetResponse;
  queryParameters?: DeclarationResponse[];
  paging?: PagingFacetResponse;
  headers?: HeadersFacetResponse;
  answers?: AnswersFacetResponse;
}
