/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSpecRequestSpecVersion } from './createSpecRequestSpecVersion';

export interface CreateSpecRequest {
  /**
     * Becomes info.title
     * @pattern \S
     */
  title: string;
  /** Becomes info.description; omitted from the document when blank */
  description?: string;
  /**
     * OpenAPI minor version, fixed after creation; defaults to 3.1 and is persisted as that minor's latest patch (FEAT-003)
     * @pattern 3\.[0-2]
     */
  specVersion?: CreateSpecRequestSpecVersion;
}
