/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */

/**
 * OpenAPI minor version, fixed after creation; defaults to 3.1 and is persisted as that minor's latest patch (FEAT-003)
 * @pattern 3\.[0-2]
 */
export type CreateSpecRequestSpecVersion = typeof CreateSpecRequestSpecVersion[keyof typeof CreateSpecRequestSpecVersion];


export const CreateSpecRequestSpecVersion = {
  '30': '3.0',
  '31': '3.1',
  '32': '3.2',
} as const;
