/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { CoreType } from './coreType';
import type { Refinement } from './refinement';

export interface DeclarationRequest {
  /**
     * Freeform name; the derived name (property-style for query parameters, Hyphenated-Capitalized for headers) is the declaration's identity
     * @maxLength 100
     * @pattern \S
     */
  name: string;
  /** The plain-language core type; omit when sending oneOfValues */
  coreType?: CoreType;
  /** Optional refinement; must belong to the core type's row */
  refinement?: Refinement;
  /** The "one of …" kind's fixed value set — trimmed, at least one, non-blank, distinct; omit when sending coreType */
  oneOfValues?: string[];
  /** On an input, whether callers must send it; on a response header, whether the answer always carries it ("always sent"). Default optional either way */
  required?: boolean;
  /** Becomes the construct's description; omitted from the document when blank */
  description?: string;
}
