/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */

export interface DescriptionRequest {
  /** The element's note for readers; blank or absent clears it — removed from the document (capability, resource) or reset to the derived default (answer) */
  description?: string;
}
