/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportFormat } from './exportFormat';

export type ExportSpecDocumentParams = {
format: ExportFormat;
};
