/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */

export type ExportFormat = typeof ExportFormat[keyof typeof ExportFormat];


export const ExportFormat = {
  yaml: 'yaml',
  json: 'json',
} as const;
