/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { CoreType } from './coreType';
import type { FieldVisibility } from './fieldVisibility';
import type { Refinement } from './refinement';

export interface FieldRequest {
  /**
     * Freeform field name; the JSON property name is derived (ADR-0011) and is the field's identity
     * @maxLength 100
     * @pattern \S
     */
  name: string;
  /** The plain-language core type (ADR-0011) */
  coreType: CoreType;
  /** Optional refinement; must belong to the core type's row */
  refinement?: Refinement;
  /** Wraps the kind as a list (array of the serialized scalar) */
  list?: boolean;
  /** Membership in the schema's required array */
  required?: boolean;
  /** Omit to apply the default — write-only for Text as password (the house rule), normal otherwise; an explicit value is honored as sent */
  visibility?: FieldVisibility;
  /** Becomes the property description; omitted from the document when blank */
  description?: string;
}
