/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { DeclarationResponse } from './declarationResponse';
import type { HeaderLineResponse } from './headerLineResponse';

export interface HeadersFacetResponse {
  derived?: HeaderLineResponse[];
  authored?: DeclarationResponse[];
}
