/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { Instant } from './instant';
import type { Uuid } from './uuid';

export interface LastEditedLocationResponse {
  specId?: Uuid;
  specTitle?: string;
  apiVersion?: string;
  capabilityName?: string;
  lastEditedAt?: Instant;
}
