/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { FieldResponse } from './fieldResponse';

export interface RequestFacetResponse {
  mergePatch?: boolean;
  fields?: FieldResponse[];
}
