/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */
import type { Instant } from './instant';
import type { Uuid } from './uuid';

export interface SpecSummaryResponse {
  id?: Uuid;
  title?: string;
  description?: string;
  apiVersion?: string;
  specVersion?: string;
  resourceCount?: number;
  operationCount?: number;
  updatedAt?: Instant;
}
