/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Apicius API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateSpecDetailsRequest {
  /**
     * Rewrites info.title
     * @pattern \S
     */
  title: string;
  /** Rewrites info.description; removed from the document when blank */
  description?: string;
  /**
     * Rewrites info.version — the API's own version, required by the OpenAPI spec; not the openapi version, which is fixed after creation
     * @pattern \S
     */
  version: string;
}
